# These are supported funding model platforms

github: [ashrafabusunaina1986]         # GitHub Sponsors
patreon:                                 # ضع اسم المستخدم إذا كنت تستخدم Patreon
open_collective:                          # ضع اسم المشروع إذا تستخدم Open Collective
ko_fi:                                    # ضع اسم المستخدم إذا تستخدم Ko-fi
tidelift:                                 # ضع اسم المشروع إذا تستخدم Tidelift
community_bridge:                         # ضع المشروع إذا تستخدم Community Bridge
liberapay:                                # ضع اسم المستخدم إذا تستخدم Liberapay
issuehunt:                                # ضع اسم المستخدم إذا تستخدم IssueHunt
lfx_crowdfunding:                         # ضع المشروع إذا تستخدم LFX Crowdfunding
polar:                                     # ضع اسم المستخدم إذا تستخدم Polar
buy_me_a_coffee:                           # ضع اسم المستخدم إذا تستخدم Buy Me a Coffee
thanks_dev:                                # ضع اسم المستخدم إذا تستخدم thanks.dev
custom: ['https://paypal.me/ashrafabusunaina1986']  # رابط دفع مباشر
